import { useEffect, useState } from "react"; import { useParams } from "react-router-dom"; import api from "../services/api";
export default function EvaluationForm(){
 const {courseId=1}=useParams(); const [questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[sent,setSent]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{api.get(`evaluations/questions/?course_id=${courseId}`).then(r=>setQuestions(r.data)).catch(console.error).finally(()=>setLoading(false))},[courseId]);
 function ans(q,v){setAnswers({...answers,[q.id]:{question:q.id,scale_value:q.question_type==="scale"?Number(v):null,text_value:q.question_type==="text"?v:""}})}
 async function submit(e){e.preventDefault();try{await api.post("evaluations/submit/",{course:Number(courseId),answers:Object.values(answers)});setSent(true)}catch{alert("Erro ao enviar avaliação.")}}
 if(loading)return <div className="public-form-page"><div className="public-form-card"><h1>Carregando formulário...</h1></div></div>;
 if(sent)return <div className="public-form-page"><div className="public-form-card success"><h1>Obrigado!</h1><p>Sua avaliação foi registrada com sucesso.</p></div></div>;
 return <div className="public-form-page"><form className="public-form-card" onSubmit={submit}><h1>Avaliação da Disciplina</h1><p>Responda de forma anônima. Sua opinião contribui para a melhoria contínua do ensino.</p>{questions.length===0&&<div className="warning-box">Nenhuma pergunta cadastrada para esta disciplina.</div>}{questions.map((q,i)=><div key={q.id} className="public-question-card"><h3>{i+1}. {q.text}</h3>{q.question_type==="scale"?<div className="scale-grid">{[{value:0,label:"Não sei avaliar"},{value:1,label:"DT"},{value:2,label:"DP"},{value:3,label:"Neutro"},{value:4,label:"CP"},{value:5,label:"CT"}].map(o=><label key={o.value} className="scale-option"><input type="radio" name={`q-${q.id}`} onChange={()=>ans(q,o.value)}/><span>{o.label}</span></label>)}</div>:<textarea placeholder="Digite sua resposta..." onChange={e=>ans(q,e.target.value)}/>}</div>)}<div className="legend-box"><strong>Legenda:</strong> DT = Discordo totalmente; DP = Discordo parcialmente; CP = Concordo parcialmente; CT = Concordo totalmente.</div><button className="public-submit-button">Enviar avaliação</button></form></div>;
}
